In [1]:
from statsmodels.stats.descriptivestats import describe
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.precision', 2)
# pd.reset_option('display.precision') # 还原精度设置

In [3]:
plt.style.use('seaborn')
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False

In [4]:
df1 = pd.read_excel('1.2铅钡.xlsx')
data1 = df1.iloc[:, 4:]

X = data1.iloc[:,1:]
y = df1.iloc[:,3]

In [5]:
# 铅钡
data1.describe()

二氧化硅(SiO2)  氧化钠(Na2O)  氧化钾(K2O)  氧化钙(CaO)  氧化镁(MgO)  氧化铝(Al2O3)  \
count       49.00      49.00     49.00     49.00     49.00       49.00   
mean        38.88       0.90      0.17      2.05      0.65        3.67   
std         18.65       1.81      0.28      1.63      0.63        3.01   
min          3.72       0.00      0.00      0.00      0.00        0.45   
25%         24.61       0.00      0.00      0.78      0.00        1.62   
50%         35.78       0.00      0.00      1.48      0.61        3.06   
75%         53.79       0.92      0.26      3.19      1.11        4.70   
max         75.51       7.92      1.41      6.40      2.73       14.34   

       氧化铁(Fe2O3)  氧化铜(CuO)  氧化铅(PbO)  氧化钡(BaO)  五氧化二磷(P2O5)  氧化锶(SrO)  \
count       49.00     49.00     49.00     49.00        49.00     49.00   
mean         0.66      1.88     33.35     10.49         3.29      0.35   
std          0.95      2.47     14.95      8.33         3.91      0.26   
min          0.00      0.00      9.30      0.00         0.00      0.00   
25%          0.00      0.47     20.12      5.68         0.14      0.20   
50%          0.23      0.79     31.90      8.94         1.41      0.31   
75%          1.03      2.72     44.12     10.88         6.04      0.47   
max          4.59     10.57     70.21     35.45        14.13      1.12   

       氧化锡(SnO2)  二氧化硫(SO2)    总含量  
count      49.00      49.00  49.00  
mean        0.06       0.80  97.19  
std         0.21       3.14   2.66  
min         0.00       0.00  88.41  
25%         0.00       0.00  96.38  
50%         0.00       0.00  98.24  
75%         0.00       0.00  98.76  
max         1.31      15.95  99.98

In [6]:
data1.skew()

二氧化硅(SiO2)     0.15
氧化钠(Na2O)      2.30
氧化钾(K2O)       2.74
氧化钙(CaO)       0.74
氧化镁(MgO)       0.76
氧化铝(Al2O3)     2.21
氧化铁(Fe2O3)     2.07
氧化铜(CuO)       2.29
氧化铅(PbO)       0.39
氧化钡(BaO)       1.61
五氧化二磷(P2O5)    1.10
氧化锶(SrO)       0.77
氧化锡(SnO2)      4.77
二氧化硫(SO2)      4.47
总含量           -1.51
dtype: float64

In [7]:
from scipy import stats
stats.kurtosis(data1, fisher=False)

array([ 1.96229381,  7.44649272, 11.24018191,  2.61778733,  3.51093772,
        7.86284066,  7.66920953,  7.61480348,  2.31945474,  4.9095462 ,
        3.06894856,  3.43108534, 26.04544545, 20.55304413,  4.75986011])

In [8]:
# 风化铅钡
X1 = data1.iloc[(y>0).values]
X1.describe()

二氧化硅(SiO2)  氧化钠(Na2O)  氧化钾(K2O)  氧化钙(CaO)  氧化镁(MgO)  氧化铝(Al2O3)  \
count       26.00      26.00     26.00     26.00     26.00       26.00   
mean        24.91       0.22      0.13      2.70      0.65        2.97   
std         10.61       0.56      0.24      1.66      0.71        2.63   
min          3.72       0.00      0.00      0.00      0.00        0.45   
25%         18.79       0.00      0.00      1.34      0.00        1.41   
50%         25.02       0.00      0.00      2.88      0.57        2.38   
75%         30.20       0.00      0.24      3.50      1.16        3.56   
max         53.33       2.22      1.05      6.40      2.73       13.65   

       氧化铁(Fe2O3)  氧化铜(CuO)  氧化铅(PbO)  氧化钡(BaO)  五氧化二磷(P2O5)  氧化锶(SrO)  \
count       26.00     26.00     26.00     26.00        26.00     26.00   
mean         0.58      2.28     43.31     11.81         5.28      0.42   
std          0.74      2.82     12.23      9.98         4.20      0.26   
min          0.00      0.00     15.71      0.00         0.00      0.00   
25%          0.00      0.71     35.47      6.78         1.31      0.23   
50%          0.30      1.15     44.06      8.79         4.97      0.42   
75%          0.99      3.14     48.84     14.51         8.59      0.59   
max          2.74     10.57     70.21     35.45        14.13      1.12   

       氧化锡(SnO2)  二氧化硫(SO2)    总含量  
count      26.00      26.00  26.00  
mean        0.07       1.37  96.69  
std         0.27       4.21   2.89  
min         0.00       0.00  90.17  
25%         0.00       0.00  94.84  
50%         0.00       0.00  97.57  
75%         0.00       0.00  98.76  
max         1.31      15.95  99.89

In [9]:
X1.skew()

二氧化硅(SiO2)     0.31
氧化钠(Na2O)      2.67
氧化钾(K2O)       2.51
氧化钙(CaO)       0.38
氧化镁(MgO)       1.04
氧化铝(Al2O3)     2.83
氧化铁(Fe2O3)     1.40
氧化铜(CuO)       2.10
氧化铅(PbO)      -0.03
氧化钡(BaO)       1.28
五氧化二磷(P2O5)    0.40
氧化锶(SrO)       0.54
氧化锡(SnO2)      4.37
二氧化硫(SO2)      3.26
总含量           -0.74
dtype: float64

In [10]:
stats.kurtosis(X1, fisher=False)

array([ 3.78332804,  8.29212988,  9.15089649,  2.40085997,  3.76659413,
       11.4776748 ,  4.02516253,  6.17447068,  2.96809641,  3.46313583,
        2.10379618,  3.41290086, 18.9590157 , 10.65645632,  2.32128614])

In [11]:
# 未风化铅钡
X2 = data1.iloc[(y==0).values]
X2.describe()

二氧化硅(SiO2)  氧化钠(Na2O)  氧化钾(K2O)  氧化钙(CaO)  氧化镁(MgO)  氧化铝(Al2O3)  \
count       23.00      23.00     23.00     23.00     23.00       23.00   
mean        54.66       1.68      0.22      1.32      0.64        4.46   
std         11.83       2.37      0.31      1.28      0.55        3.26   
min         31.94       0.00      0.00      0.00      0.00        1.42   
25%         49.81       0.00      0.00      0.48      0.00        2.35   
50%         54.61       0.00      0.15      0.84      0.71        3.86   
75%         63.48       2.88      0.28      1.84      1.04        5.22   
max         75.51       7.92      1.41      4.49      1.67       14.34   

       氧化铁(Fe2O3)  氧化铜(CuO)  氧化铅(PbO)  氧化钡(BaO)  五氧化二磷(P2O5)  氧化锶(SrO)  \
count       23.00     23.00     23.00     23.00        23.00     23.00   
mean         0.74      1.43     22.08      9.00         1.05      0.27   
std          1.15      1.97      8.22      5.83         1.85      0.24   
min          0.00      0.00      9.30      2.03         0.00      0.00   
25%          0.00      0.43     16.36      5.05         0.04      0.06   
50%          0.00      0.65     20.12      8.99         0.19      0.26   
75%          1.14      1.90     27.27     10.41         1.23      0.34   
max          4.59      8.46     39.22     26.23         6.34      0.91   

       氧化锡(SnO2)  二氧化硫(SO2)    总含量  
count      23.00      23.00  23.00  
mean        0.05       0.16  97.76  
std         0.13       0.76   2.30  
min         0.00       0.00  88.41  
25%         0.00       0.00  97.16  
50%         0.00       0.00  98.25  
75%         0.00       0.00  98.70  
max         0.44       3.66  99.98

In [12]:
X2.skew()

二氧化硅(SiO2)    -0.37
氧化钠(Na2O)      1.29
氧化钾(K2O)       2.88
氧化钙(CaO)       1.35
氧化镁(MgO)       0.09
氧化铝(Al2O3)     1.99
氧化铁(Fe2O3)     2.07
氧化铜(CuO)       2.46
氧化铅(PbO)       0.62
氧化钡(BaO)       1.80
五氧化二磷(P2O5)    2.17
氧化锶(SrO)       1.23
氧化锡(SnO2)      2.63
二氧化硫(SO2)      4.80
总含量           -3.20
dtype: float64

In [13]:
stats.kurtosis(X2, fisher=False)

array([ 2.32225372,  3.35299648, 10.75298965,  3.56941997,  1.76305699,
        6.11721174,  6.54298946,  8.22035961,  2.38700241,  5.73909559,
        5.71249649,  4.30875217,  7.3761559 , 21.04545455, 13.015012  ])

In [14]:
# 铅钡组未风化均值 比 风化后均值
rate1 = X2.mean()/X1.mean()
rate1

二氧化硅(SiO2)     2.19
氧化钠(Na2O)      7.78
氧化钾(K2O)       1.64
氧化钙(CaO)       0.49
氧化镁(MgO)       0.99
氧化铝(Al2O3)     1.50
氧化铁(Fe2O3)     1.26
氧化铜(CuO)       0.63
氧化铅(PbO)       0.51
氧化钡(BaO)       0.76
五氧化二磷(P2O5)    0.20
氧化锶(SrO)       0.64
氧化锡(SnO2)      0.68
二氧化硫(SO2)      0.12
总含量            1.01
dtype: float64

In [15]:
df1

文物编号    文物采样点  类型  风化与否  二氧化硅(SiO2)  氧化钠(Na2O)  氧化钾(K2O)  氧化钙(CaO)  \
0      2       02  铅钡     1       36.28       0.00      1.05      2.34   
1      8       08  铅钡     1       20.14       0.00      0.00      1.48   
2      8  08严重风化点  铅钡     2        4.61       0.00      0.00      3.19   
3     11       11  铅钡     1       33.59       0.00      0.21      3.51   
4     19       19  铅钡     1       29.64       0.00      0.00      2.93   
5     20       20  铅钡     0       37.36       0.00      0.71      0.00   
6     23   23未风化点  铅钡     0       53.79       7.92      0.00      0.50   
7     24       24  铅钡     0       31.94       0.00      0.00      0.47   
8     25   25未风化点  铅钡     0       50.61       2.31      0.00      0.63   
9     26       26  铅钡     1       19.79       0.00      0.00      1.44   
10    26  26严重风化点  铅钡     2        3.72       0.00      0.40      3.01   
11    28   28未风化点  铅钡     0       68.08       0.00      0.26      1.34   
12    29   29未风化点  铅钡     0       63.30       0.92      0.30      2.98   
13    30    30部位1  铅钡     0       34.34       0.00      1.41      4.49   
14    30    30部位2  铅钡     0       36.93       0.00      0.00      4.24   
15    31       31  铅钡     0       65.91       0.00      0.00      1.60   
16    32       32  铅钡     0       69.71       0.00      0.21      0.46   
17    33       33  铅钡     0       75.51       0.00      0.15      0.64   
18    34       34  铅钡     1       35.78       0.00      0.25      0.78   
19    35       35  铅钡     0       65.91       0.00      0.00      0.38   
20    36       36  铅钡     1       39.57       2.22      0.14      0.37   
21    37       37  铅钡     0       60.12       0.00      0.23      0.89   
22    38       38  铅钡     1       32.93       1.38      0.00      0.68   
23    39       39  铅钡     1       26.25       0.00      0.00      1.11   
24    40       40  铅钡     1       16.71       0.00      0.00      1.87   
25    41       41  铅钡     1       18.46       0.00      0.44      4.96   
26    42  42未风化点1  铅钡     0       51.26       5.74      0.15      0.79   
27    42  42未风化点2  铅钡     0       51.33       5.68      0.35      0.00   
28    43    43部位1  铅钡     1       12.41       0.00      0.00      5.24   
29    43    43部位2  铅钡     1       21.70       0.00      0.00      6.40   
30    44   44未风化点  铅钡     0       60.74       3.06      0.20      2.14   
31    45       45  铅钡     0       61.28       2.66      0.11      0.84   
32    46       46  铅钡     0       55.21       0.00      0.25      0.00   
33    47       47  铅钡     0       51.54       4.66      0.29      0.87   
34    48       48  铅钡     1       53.33       0.80      0.32      2.82   
35    49       49  铅钡     1       28.79       0.00      0.00      4.58   
36    49   49未风化点  铅钡     0       54.61       0.00      0.30      2.08   
37    50       50  铅钡     1       17.98       0.00      0.00      3.19   
38    50   50未风化点  铅钡     0       45.02       0.00      0.00      3.12   
39    51    51部位1  铅钡     1       24.61       0.00      0.00      3.58   
40    51    51部位2  铅钡     1       21.35       0.00      0.00      5.13   
41    52       52  铅钡     1       25.74       1.22      0.00      2.27   
42    53   53未风化点  铅钡     0       63.66       3.04      0.11      0.78   
43    54       54  铅钡     1       22.28       0.00      0.32      3.19   
44    54  54严重风化点  铅钡     2       17.11       0.00      0.00      0.00   
45    55       55  铅钡     0       49.01       2.71      0.00      1.13   
46    56       56  铅钡     1       29.15       0.00      0.00      1.21   
47    57       57  铅钡     1       25.42       0.00      0.00      1.31   
48    58       58  铅钡     1       30.39       0.00      0.34      3.49   

    氧化镁(MgO)  氧化铝(Al2O3)  氧化铁(Fe2O3)  氧化铜(CuO)  氧化铅(PbO)  氧化钡(BaO)  \
0       1.18        5.73        1.86      0.26     47.43      0.00   
1       0.00        1.34        0.00     10.41     28.68     31.23   
2       0.00        1.11        0.00      3.14     32.45     30.62   
3       0.71        2.6

In [16]:
dc = df1.iloc[(y>0).values,[1,*range(4,df1.shape[1])]].copy()

lb1 = X1*rate1*0.95
ub1 = X1*rate1*1.05

lb1 = round(lb1, 2)
ub1 = round(ub1, 2)

ls = []
for i in range(lb1.shape[0]):
    l = []
    for j in range(lb1.shape[1]):
        l.append((lb1.iloc[i,j], ub1.iloc[i,j]))
    ls.append(l)

pd.DataFrame(ls, index=dc['文物采样点'], columns=X1.columns).to_excel('1.1铅钡风化前预测.xlsx')

In [17]:
df2 = pd.read_excel('1.2高钾.xlsx')
data2 = df2.iloc[:, 4:]

X = data2.iloc[:,1:]
y = df2.iloc[:,3]

In [18]:
# 高钾
data2.describe()

二氧化硅(SiO2)  氧化钠(Na2O)  氧化钾(K2O)  氧化钙(CaO)  氧化镁(MgO)  氧化铝(Al2O3)  \
count       18.00      18.00     18.00     18.00     18.00       18.00   
mean        76.64       0.46      6.40      3.84      0.79        5.06   
std         14.47       1.09      5.31      3.31      0.71        3.08   
min         59.01       0.00      0.00      0.00      0.00        0.81   
25%         63.15       0.00      0.79      0.77      0.00        2.64   
50%         73.00       0.00      7.53      3.36      0.65        4.78   
75%         92.56       0.00     10.71      6.92      1.45        6.38   
max         96.77       3.38     14.52      8.70      1.98       11.15   

       氧化铁(Fe2O3)  氧化铜(CuO)  氧化铅(PbO)  氧化钡(BaO)  五氧化二磷(P2O5)  氧化锶(SrO)  \
count       18.00     18.00     18.00     18.00        18.00     18.00   
mean         1.38      2.16      0.27      0.40         1.03      0.03   
std          1.57      1.49      0.51      0.84         1.28      0.04   
min          0.00      0.00      0.00      0.00         0.00      0.00   
25%          0.27      0.90      0.00      0.00         0.24      0.00   
50%          0.46      1.92      0.00      0.00         0.68      0.00   
75%          2.32      3.26      0.24      0.00         1.15      0.06   
max          6.04      5.09      1.62      2.86         4.50      0.12   

       氧化锡(SnO2)  二氧化硫(SO2)     总含量  
count      18.00      18.00   18.00  
mean        0.13       0.07   98.66  
std         0.56       0.16    1.17  
min         0.00       0.00   96.06  
25%         0.00       0.00   98.21  
50%         0.00       0.00   98.86  
75%         0.00       0.00   99.67  
max         2.36       0.47  100.00

In [19]:
data2.skew()

二氧化硅(SiO2)     0.21
氧化钠(Na2O)      2.13
氧化钾(K2O)      -0.04
氧化钙(CaO)       0.19
氧化镁(MgO)       0.29
氧化铝(Al2O3)     0.48
氧化铁(Fe2O3)     1.63
氧化铜(CuO)       0.51
氧化铅(PbO)       1.97
氧化钡(BaO)       2.11
五氧化二磷(P2O5)    2.15
氧化锶(SrO)       1.23
氧化锡(SnO2)      4.24
二氧化硫(SO2)      2.03
总含量           -0.90
dtype: float64

In [20]:
stats.kurtosis(data2, fisher=False)

array([ 1.33451926,  5.01979891,  1.41007204,  1.3601897 ,  1.64537805,
        2.21845307,  5.19039263,  2.20909788,  4.70716694,  5.48280691,
        5.74955659,  2.63550035, 16.05882353,  4.54910707,  2.80085483])

In [21]:
# 风化高钾
X3 = data2.iloc[(y>0).values]
X3.describe()

二氧化硅(SiO2)  氧化钠(Na2O)  氧化钾(K2O)  氧化钙(CaO)  氧化镁(MgO)  氧化铝(Al2O3)  \
count        6.00        6.0      6.00      6.00      6.00        6.00   
mean        93.96        0.0      0.54      0.87      0.20        1.93   
std          1.73        0.0      0.45      0.49      0.31        0.96   
min         92.35        0.0      0.00      0.21      0.00        0.81   
25%         92.65        0.0      0.15      0.65      0.00        1.35   
50%         93.50        0.0      0.67      0.83      0.00        1.72   
75%         94.84        0.0      0.88      1.04      0.41        2.38   
max         96.77        0.0      1.01      1.66      0.64        3.50   

       氧化铁(Fe2O3)  氧化铜(CuO)  氧化铅(PbO)  氧化钡(BaO)  五氧化二磷(P2O5)  氧化锶(SrO)  \
count        6.00      6.00       6.0       6.0         6.00       6.0   
mean         0.27      1.56       0.0       0.0         0.28       0.0   
std          0.07      0.93       0.0       0.0         0.21       0.0   
min          0.17      0.55       0.0       0.0         0.00       0.0   
25%          0.22      1.01       0.0       0.0         0.16       0.0   
50%          0.28      1.54       0.0       0.0         0.28       0.0   
75%          0.31      1.62       0.0       0.0         0.36       0.0   
max          0.35      3.24       0.0       0.0         0.61       0.0   

       氧化锡(SnO2)  二氧化硫(SO2)     总含量  
count        6.0        6.0    6.00  
mean         0.0        0.0   99.61  
std          0.0        0.0    0.42  
min          0.0        0.0   98.81  
25%          0.0        0.0   99.60  
50%          0.0        0.0   99.73  
75%          0.0        0.0   99.80  
max          0.0        0.0  100.00

In [22]:
X3.skew()

二氧化硅(SiO2)     0.85
氧化钠(Na2O)      0.00
氧化钾(K2O)      -0.54
氧化钙(CaO)       0.50
氧化镁(MgO)       1.01
氧化铝(Al2O3)     0.78
氧化铁(Fe2O3)    -0.30
氧化铜(CuO)       1.22
氧化铅(PbO)       0.00
氧化钡(BaO)       0.00
五氧化二磷(P2O5)    0.40
氧化锶(SrO)       0.00
氧化锡(SnO2)      0.00
二氧化硫(SO2)      0.00
总含量           -1.83
dtype: float64

In [23]:
stats.kurtosis(X3, fisher=False)

array([2.00968737, 0.        , 1.48697993, 2.48151266, 1.59506962,
       2.20480786, 1.65676479, 2.90791259, 0.        , 0.        ,
       2.27029391, 0.        , 0.        , 0.        , 3.46944106])

In [24]:
# 未风化高钾
X4 = data2.iloc[(y==0).values]
X4.describe()

二氧化硅(SiO2)  氧化钠(Na2O)  氧化钾(K2O)  氧化钙(CaO)  氧化镁(MgO)  氧化铝(Al2O3)  \
count       12.00      12.00     12.00     12.00     12.00       12.00   
mean        67.98       0.69      9.33      5.33      1.08        6.62   
std          8.76       1.29      3.92      3.09      0.68        2.49   
min         59.01       0.00      0.00      0.00      0.00        3.05   
25%         61.68       0.00      7.60      4.04      0.62        5.14   
50%         65.53       0.00      9.83      6.10      1.17        6.19   
75%         71.17       0.53     12.30      7.57      1.60        7.93   
max         87.05       3.38     14.52      8.70      1.98       11.15   

       氧化铁(Fe2O3)  氧化铜(CuO)  氧化铅(PbO)  氧化钡(BaO)  五氧化二磷(P2O5)  氧化锶(SrO)  \
count       12.00     12.00     12.00     12.00        12.00     12.00   
mean         1.93      2.45      0.41      0.60         1.40      0.04   
std          1.67      1.66      0.59      0.98         1.43      0.05   
min          0.00      0.00      0.00      0.00         0.00      0.00   
25%          0.48      1.00      0.00      0.00         0.69      0.00   
50%          2.11      2.34      0.15      0.00         1.02      0.02   
75%          2.45      3.43      0.51      1.07         1.29      0.08   
max          6.04      5.09      1.62      2.86         4.50      0.12   

       氧化锡(SnO2)  二氧化硫(SO2)     总含量  
count      12.00      12.00   12.00  
mean        0.20       0.10   98.18  
std         0.68       0.19    1.13  
min         0.00       0.00   96.06  
25%         0.00       0.00   97.52  
50%         0.00       0.00   98.46  
75%         0.00       0.09   98.89  
max         2.36       0.47  100.00

In [25]:
X4.skew()

二氧化硅(SiO2)     1.16
氧化钠(Na2O)      1.50
氧化钾(K2O)      -1.20
氧化钙(CaO)      -0.88
氧化镁(MgO)      -0.43
氧化铝(Al2O3)     0.48
氧化铁(Fe2O3)     1.18
氧化铜(CuO)       0.10
氧化铅(PbO)       1.37
氧化钡(BaO)       1.49
五氧化二磷(P2O5)    1.68
氧化锶(SrO)       0.57
氧化锡(SnO2)      3.46
二氧化硫(SO2)      1.40
总含量           -0.56
dtype: float64

In [26]:
stats.kurtosis(X4, fisher=False)

array([ 2.87603899,  2.89038773,  3.73447461,  2.21263928,  1.89990917,
        2.22865668,  4.15465249,  1.87245262,  2.80151776,  3.31772944,
        3.71928505,  1.62446509, 10.09090909,  2.57336846,  2.471381  ])

In [27]:
# 高钾组未风化均值 比 风化后均值
rate2 = X4.mean()/X3.mean()
rate2

二氧化硅(SiO2)      0.72
氧化钠(Na2O)        inf
氧化钾(K2O)       17.17
氧化钙(CaO)        6.13
氧化镁(MgO)        5.49
氧化铝(Al2O3)      3.43
氧化铁(Fe2O3)      7.29
氧化铜(CuO)        1.57
氧化铅(PbO)         inf
氧化钡(BaO)         inf
五氧化二磷(P2O5)     5.01
氧化锶(SrO)         inf
氧化锡(SnO2)        inf
二氧化硫(SO2)        inf
总含量             0.99
dtype: float64

In [28]:
dc = df2.iloc[(y>0).values,[1,*range(4,df2.shape[1])]].copy()

In [29]:
lb2 = X3*rate2*0.95
ub2 = X3*rate2*1.05

lb2.fillna(0, inplace=True)
ub2.fillna(0, inplace=True)

lb2 = round(lb2, 2)
ub2 = round(ub2, 2)

ls = []
for i in range(lb2.shape[0]):
    l = []
    for j in range(lb2.shape[1]):
        l.append((lb2.iloc[i,j], ub2.iloc[i,j]))
    ls.append(l)

pd.DataFrame(ls, index=dc['文物采样点'], columns=X3.columns).to_excel('1.1高钾风化前预测.xlsx')

In [30]:
df = pd.DataFrame(rate1,columns=['铅钡组均值风化前后比值'])
df['高钾组均值风化前后比值'] = rate2.fillna(0)
df_new = pd.DataFrame(df.values.T, index=df.columns, columns=df.index)
df_new
df_new.to_excel('./1.2预测/比值.xlsx')

In [34]:
# 描述性统计
def descriptive_statistics(df):
    skew_list = []
    kurt_list = []
    description = df.describe()
    for i in df.iteritems():
        skew_list.append(i[1].skew())
        # pandas自带的kurtosis计算偏度是是无偏的（除了n-1）
        # stats里面是有偏的（除了n)
        # 课件里MATLAB的值有偏
        kurt_list.append(stats.kurtosis(i[1], fisher=False))
    description.loc["skew"] = skew_list
    description.loc["kurt"] = kurt_list
    return description


round(descriptive_statistics(X2),2).to_csv('./描述性统计/铅钡未风化描述性统计.csv',encoding='utf-8-sig')  # 不加sig中文会乱码
round(descriptive_statistics(X1),2).to_csv('./描述性统计/铅钡风化描述性统计.csv',encoding='utf-8-sig')
round(descriptive_statistics(X3),2).to_csv('./描述性统计/高钾风化描述性统计.csv',encoding='utf-8-sig')  # 不加sig中文会乱码
round(descriptive_statistics(X4),2).to_csv('./描述性统计/高钾未风化描述性统计.csv',encoding='utf-8-sig')